from io import BytesIO
import aiohttp
from openai import AsyncOpenAI

from fastapi import FastAPI

from app.misc.constants import SECRETS

app = FastAPI()

async def generate_image_via_dalle(description):
    print("Generating image via DALL-E...")

    # Initialize the OpenAI client
    client = AsyncOpenAI(api_key=SECRETS.OPENAI_KEY)

    try:
        # Call the DALL-E API to generate an image
        response = await client.images.generate(
            model="dall-e-3",
            prompt=description,
            size="1024x1024",
            quality="standard",
            n=1,
        )

        # Get the image URL from the response
        image_url = response.data[0].url

        # Download the image
        async with aiohttp.ClientSession() as session:
            async with session.get(image_url) as image_response:
                if image_response.status == 200:
                    print("Image generated by DALL-E")
                    image_data = await image_response.read()
                    return BytesIO(image_data)
                else:
                    raise Exception("Failed to download image from DALL-E URL")

    except Exception as e:
        print(f"Error during DALL-E image generation: {e}")
        raise
